### ISSUE TITLE
Node crashes node-red with uncaught exception

### ISSUE THREAD

**Issue by ndrsfr** [dehsgr/node-red-contrib-alphaess#2]
Hi,

first of all: many thanks for the really good implementation of the node to perfectly integrate my AlphaESS storage into my smart home.

However, in some cases the node seems to crash my nodered instance.
Today it was the case again. Luckily I was at the computer at the same time and directly checked logging into "cloud.alphaess.com" which did not work as well -> response from the website in Chinese: "Network issue (502)"

Please find the error log for the node from my nodered instance attached:

```
12 Jul 13:51:59 - [red] Uncaught Exception:
12 Jul 13:51:59 - [error] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/data/node_modules/node-red-contrib-alphaess/alphaess-monitoring.js:386:21)
    at Request.self.callback (/data/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/data/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/data/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1

 
npm ERR! Failed at the node-red-docker@2.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /data/.npm/_logs/2022-07-12T13_51_59_826Z-debug.log
```

Would it possible to catch the exception so that nodered will not crash the next time this happens?
Please let me know if I can support with any more details or be a help with testing.

Many thanks
Andreas

P.S. This is my first reported GitHub issue. Hope I am doing it right ;-)

**Comment by dehsgr** [comment]
Thanks for reporting this. A new package version has been published.
